version: 0.0
os: linux
files:
  - source: AwsDeveloperProject.jar
    destination: /home/ec2-user/
  - source: start_server.sh
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
    - location: /bin/bash
      timeout: 300
      runas: ec2-user
      commands:
        - sudo chmod +x /home/ec2-user/start_server.sh

  AfterInstall:
    - location: /home/ec2-user/start_server.sh
      timeout: 300
      runas: ec2-user