Parameters:
  AWSRegion:
    Type: String
    Default: us-west-2
    Description: "Region where resources will be deployed"
  DBUsername:
    Type: String
    Description: "The master username for the RDS instance."
    Default: "admin"
  DBPassword:
    Type: String
    Description: "The master password for the RDS instance."
    NoEcho: true


Resources:
  DataConsistencyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Ivan-Kukushkin-Project-DataConsistencyFunction
      Handler: com.epam.aws.lambda.DataConsistencyHandler::handleRequest
      Runtime: java17
      MemorySize: 512
      Timeout: 30
      Role: !ImportValue LambdaExecutionRole
      Environment:
        Variables:
          DB_ENDPOINT: !ImportValue RdsInstanceEndpoint
          DB_NAME: !ImportValue RdsDatabaseName
          S3_BUCKET: !ImportValue S3BucketName
          AWS_REGION: !Ref AWSRegion

  DataConsistencyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /check-consistency:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DataConsistencyFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
                requestTemplates:
                  application/json: '{"detail-type": "APIGateway"}'

  DataConsistencyScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(5 minutes)
      Targets:
        - Arn: !GetAtt DataConsistencyFunction.Arn
          Id: "DataConsistencyFunctionTarget"
