AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3LogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Ivan-Kukushkin-Project-S3LogsFunction
      Handler: com.epam.aws.lambda.S3LogsHandler::handleRequest
      Runtime: java17
      MemorySize: 512
      Timeout: 30
      Role: !ImportValue LambdaExecutionRole
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region

  S3EventNotification:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !ImportValue S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt S3LogsFunction.Arn
    DependsOn: S3LogsFunction

Outputs:
  LambdaFunctionArn:
    Value: !GetAtt S3LogsFunction.Arn
