AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AwsDeveloper-Project-UploadsNotificationFunction
      Handler: com.epam.aws.lambda.UploadsNotificationHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Role: !ImportValue LambdaExecutionRole
      Timeout: 30
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !ImportValue UploadsNotificationQueueArn
      Environment:
        Variables:
          SNS_TOPIC_ARN: !ImportValue UploadsNotificationTopicArn
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce